package com.fanren.wx.app.pojo;

public class Attend {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attend_list.student_ID
     *
     * @mbg.generated Wed Feb 27 15:59:07 CST 2019
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attend_list.student_name
     *
     * @mbg.generated Wed Feb 27 15:59:07 CST 2019
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attend_list.class_name
     *
     * @mbg.generated Wed Feb 27 15:59:07 CST 2019
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attend_list.time
     *
     * @mbg.generated Wed Feb 27 15:59:07 CST 2019
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attend_list.student_ID
     *
     * @return the value of attend_list.student_ID
     *
     * @mbg.generated Wed Feb 27 15:59:07 CST 2019
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attend_list.student_ID
     *
     * @param studentId the value for attend_list.student_ID
     *
     * @mbg.generated Wed Feb 27 15:59:07 CST 2019
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attend_list.student_name
     *
     * @return the value of attend_list.student_name
     *
     * @mbg.generated Wed Feb 27 15:59:07 CST 2019
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attend_list.student_name
     *
     * @param studentName the value for attend_list.student_name
     *
     * @mbg.generated Wed Feb 27 15:59:07 CST 2019
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attend_list.class_name
     *
     * @return the value of attend_list.class_name
     *
     * @mbg.generated Wed Feb 27 15:59:07 CST 2019
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attend_list.class_name
     *
     * @param className the value for attend_list.class_name
     *
     * @mbg.generated Wed Feb 27 15:59:07 CST 2019
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attend_list.time
     *
     * @return the value of attend_list.time
     *
     * @mbg.generated Wed Feb 27 15:59:07 CST 2019
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attend_list.time
     *
     * @param time the value for attend_list.time
     *
     * @mbg.generated Wed Feb 27 15:59:07 CST 2019
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }
}