package com.fanren.wx.app.pojo;

import java.io.Serializable;

public class Badworld implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column badworld_list.BadWorld
     *
     * @mbg.generated Thu Feb 21 12:44:58 CST 2019
     */
    private String badworld;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column badworld_list.BadWorld
     *
     * @return the value of badworld_list.BadWorld
     *
     * @mbg.generated Thu Feb 21 12:44:58 CST 2019
     */
    public String getBadworld() {
        return badworld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column badworld_list.BadWorld
     *
     * @param badworld the value for badworld_list.BadWorld
     *
     * @mbg.generated Thu Feb 21 12:44:58 CST 2019
     */
    public void setBadworld(String badworld) {
        this.badworld = badworld == null ? null : badworld.trim();
    }
}