package com.fanren.wx.app.pojo;

public class Class {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_list.class_ID
     *
     * @mbg.generated Mon Feb 11 10:15:00 CST 2019
     */
    private String classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_list.major_ID
     *
     * @mbg.generated Mon Feb 11 10:15:00 CST 2019
     */
    private String majorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_list.student_number
     *
     * @mbg.generated Mon Feb 11 10:15:00 CST 2019
     */
    private String studentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_list.headmaster_ID
     *
     * @mbg.generated Mon Feb 11 10:15:00 CST 2019
     */
    private String headmasterId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_list.class_ID
     *
     * @return the value of class_list.class_ID
     *
     * @mbg.generated Mon Feb 11 10:15:00 CST 2019
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_list.class_ID
     *
     * @param classId the value for class_list.class_ID
     *
     * @mbg.generated Mon Feb 11 10:15:00 CST 2019
     */
    public void setClassId(String classId) {
        this.classId = classId == null ? null : classId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_list.major_ID
     *
     * @return the value of class_list.major_ID
     *
     * @mbg.generated Mon Feb 11 10:15:00 CST 2019
     */
    public String getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_list.major_ID
     *
     * @param majorId the value for class_list.major_ID
     *
     * @mbg.generated Mon Feb 11 10:15:00 CST 2019
     */
    public void setMajorId(String majorId) {
        this.majorId = majorId == null ? null : majorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_list.student_number
     *
     * @return the value of class_list.student_number
     *
     * @mbg.generated Mon Feb 11 10:15:00 CST 2019
     */
    public String getStudentNumber() {
        return studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_list.student_number
     *
     * @param studentNumber the value for class_list.student_number
     *
     * @mbg.generated Mon Feb 11 10:15:00 CST 2019
     */
    public void setStudentNumber(String studentNumber) {
        this.studentNumber = studentNumber == null ? null : studentNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_list.headmaster_ID
     *
     * @return the value of class_list.headmaster_ID
     *
     * @mbg.generated Mon Feb 11 10:15:00 CST 2019
     */
    public String getHeadmasterId() {
        return headmasterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_list.headmaster_ID
     *
     * @param headmasterId the value for class_list.headmaster_ID
     *
     * @mbg.generated Mon Feb 11 10:15:00 CST 2019
     */
    public void setHeadmasterId(String headmasterId) {
        this.headmasterId = headmasterId == null ? null : headmasterId.trim();
    }
}