package com.fanren.wx.app.pojo;

public class College {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college_list.college_ID
     *
     * @mbg.generated Thu Jan 31 09:50:32 CST 2019
     */
    private String collegeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college_list.name
     *
     * @mbg.generated Thu Jan 31 09:50:32 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college_list.college_ID
     *
     * @return the value of college_list.college_ID
     *
     * @mbg.generated Thu Jan 31 09:50:32 CST 2019
     */
    public String getCollegeId() {
        return collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college_list.college_ID
     *
     * @param collegeId the value for college_list.college_ID
     *
     * @mbg.generated Thu Jan 31 09:50:32 CST 2019
     */
    public void setCollegeId(String collegeId) {
        this.collegeId = collegeId == null ? null : collegeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college_list.name
     *
     * @return the value of college_list.name
     *
     * @mbg.generated Thu Jan 31 09:50:32 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college_list.name
     *
     * @param name the value for college_list.name
     *
     * @mbg.generated Thu Jan 31 09:50:32 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}