package com.fanren.wx.app.pojo;

public class Curriculum {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum_list.kcmc
     *
     * @mbg.generated Fri Mar 01 11:06:52 CST 2019
     */
    private String kcmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum_list.kcdd
     *
     * @mbg.generated Fri Mar 01 11:06:52 CST 2019
     */
    private String kcdd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum_list.teachers
     *
     * @mbg.generated Fri Mar 01 11:06:52 CST 2019
     */
    private String teachers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum_list.skbj
     *
     * @mbg.generated Fri Mar 01 11:06:52 CST 2019
     */
    private String skbj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum_list.week_time
     *
     * @mbg.generated Fri Mar 01 11:06:52 CST 2019
     */
    private String weekTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum_list.day_time
     *
     * @mbg.generated Fri Mar 01 11:06:52 CST 2019
     */
    private String dayTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum_list.zhouci
     *
     * @mbg.generated Fri Mar 01 11:06:52 CST 2019
     */
    private String zhouci;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum_list.kcmc
     *
     * @return the value of curriculum_list.kcmc
     *
     * @mbg.generated Fri Mar 01 11:06:52 CST 2019
     */
    public String getKcmc() {
        return kcmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum_list.kcmc
     *
     * @param kcmc the value for curriculum_list.kcmc
     *
     * @mbg.generated Fri Mar 01 11:06:52 CST 2019
     */
    public void setKcmc(String kcmc) {
        this.kcmc = kcmc == null ? null : kcmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum_list.kcdd
     *
     * @return the value of curriculum_list.kcdd
     *
     * @mbg.generated Fri Mar 01 11:06:52 CST 2019
     */
    public String getKcdd() {
        return kcdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum_list.kcdd
     *
     * @param kcdd the value for curriculum_list.kcdd
     *
     * @mbg.generated Fri Mar 01 11:06:52 CST 2019
     */
    public void setKcdd(String kcdd) {
        this.kcdd = kcdd == null ? null : kcdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum_list.teachers
     *
     * @return the value of curriculum_list.teachers
     *
     * @mbg.generated Fri Mar 01 11:06:52 CST 2019
     */
    public String getTeachers() {
        return teachers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum_list.teachers
     *
     * @param teachers the value for curriculum_list.teachers
     *
     * @mbg.generated Fri Mar 01 11:06:52 CST 2019
     */
    public void setTeachers(String teachers) {
        this.teachers = teachers == null ? null : teachers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum_list.skbj
     *
     * @return the value of curriculum_list.skbj
     *
     * @mbg.generated Fri Mar 01 11:06:52 CST 2019
     */
    public String getSkbj() {
        return skbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum_list.skbj
     *
     * @param skbj the value for curriculum_list.skbj
     *
     * @mbg.generated Fri Mar 01 11:06:52 CST 2019
     */
    public void setSkbj(String skbj) {
        this.skbj = skbj == null ? null : skbj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum_list.week_time
     *
     * @return the value of curriculum_list.week_time
     *
     * @mbg.generated Fri Mar 01 11:06:52 CST 2019
     */
    public String getWeekTime() {
        return weekTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum_list.week_time
     *
     * @param weekTime the value for curriculum_list.week_time
     *
     * @mbg.generated Fri Mar 01 11:06:52 CST 2019
     */
    public void setWeekTime(String weekTime) {
        this.weekTime = weekTime == null ? null : weekTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum_list.day_time
     *
     * @return the value of curriculum_list.day_time
     *
     * @mbg.generated Fri Mar 01 11:06:52 CST 2019
     */
    public String getDayTime() {
        return dayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum_list.day_time
     *
     * @param dayTime the value for curriculum_list.day_time
     *
     * @mbg.generated Fri Mar 01 11:06:52 CST 2019
     */
    public void setDayTime(String dayTime) {
        this.dayTime = dayTime == null ? null : dayTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum_list.zhouci
     *
     * @return the value of curriculum_list.zhouci
     *
     * @mbg.generated Fri Mar 01 11:06:52 CST 2019
     */
    public String getZhouci() {
        return zhouci;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum_list.zhouci
     *
     * @param zhouci the value for curriculum_list.zhouci
     *
     * @mbg.generated Fri Mar 01 11:06:52 CST 2019
     */
    public void setZhouci(String zhouci) {
        this.zhouci = zhouci == null ? null : zhouci.trim();
    }
}