package com.fanren.wx.app.pojo;

public class Exam {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_list.name
     *
     * @mbg.generated Sat Mar 02 14:58:00 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_list.time
     *
     * @mbg.generated Sat Mar 02 14:58:00 CST 2019
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_list.place
     *
     * @mbg.generated Sat Mar 02 14:58:00 CST 2019
     */
    private String place;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_list.teacher
     *
     * @mbg.generated Sat Mar 02 14:58:00 CST 2019
     */
    private String teacher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_list.classes
     *
     * @mbg.generated Sat Mar 02 14:58:00 CST 2019
     */
    private String classes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_list.name
     *
     * @return the value of exam_list.name
     *
     * @mbg.generated Sat Mar 02 14:58:00 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_list.name
     *
     * @param name the value for exam_list.name
     *
     * @mbg.generated Sat Mar 02 14:58:00 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_list.time
     *
     * @return the value of exam_list.time
     *
     * @mbg.generated Sat Mar 02 14:58:00 CST 2019
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_list.time
     *
     * @param time the value for exam_list.time
     *
     * @mbg.generated Sat Mar 02 14:58:00 CST 2019
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_list.place
     *
     * @return the value of exam_list.place
     *
     * @mbg.generated Sat Mar 02 14:58:00 CST 2019
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_list.place
     *
     * @param place the value for exam_list.place
     *
     * @mbg.generated Sat Mar 02 14:58:00 CST 2019
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_list.teacher
     *
     * @return the value of exam_list.teacher
     *
     * @mbg.generated Sat Mar 02 14:58:00 CST 2019
     */
    public String getTeacher() {
        return teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_list.teacher
     *
     * @param teacher the value for exam_list.teacher
     *
     * @mbg.generated Sat Mar 02 14:58:00 CST 2019
     */
    public void setTeacher(String teacher) {
        this.teacher = teacher == null ? null : teacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_list.classes
     *
     * @return the value of exam_list.classes
     *
     * @mbg.generated Sat Mar 02 14:58:00 CST 2019
     */
    public String getClasses() {
        return classes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_list.classes
     *
     * @param classes the value for exam_list.classes
     *
     * @mbg.generated Sat Mar 02 14:58:00 CST 2019
     */
    public void setClasses(String classes) {
        this.classes = classes == null ? null : classes.trim();
    }
}