package com.fanren.wx.app.pojo;

public class Inform {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inform_list.title
     *
     * @mbg.generated Sat Mar 02 16:55:26 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inform_list.time
     *
     * @mbg.generated Sat Mar 02 16:55:26 CST 2019
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inform_list.content
     *
     * @mbg.generated Sat Mar 02 16:55:26 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inform_list.annex_dir
     *
     * @mbg.generated Sat Mar 02 16:55:26 CST 2019
     */
    private String annexDir;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inform_list.annex_title
     *
     * @mbg.generated Sat Mar 02 16:55:26 CST 2019
     */
    private String annexTitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inform_list.title
     *
     * @return the value of inform_list.title
     *
     * @mbg.generated Sat Mar 02 16:55:26 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inform_list.title
     *
     * @param title the value for inform_list.title
     *
     * @mbg.generated Sat Mar 02 16:55:26 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inform_list.time
     *
     * @return the value of inform_list.time
     *
     * @mbg.generated Sat Mar 02 16:55:26 CST 2019
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inform_list.time
     *
     * @param time the value for inform_list.time
     *
     * @mbg.generated Sat Mar 02 16:55:26 CST 2019
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inform_list.content
     *
     * @return the value of inform_list.content
     *
     * @mbg.generated Sat Mar 02 16:55:26 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inform_list.content
     *
     * @param content the value for inform_list.content
     *
     * @mbg.generated Sat Mar 02 16:55:26 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inform_list.annex_dir
     *
     * @return the value of inform_list.annex_dir
     *
     * @mbg.generated Sat Mar 02 16:55:26 CST 2019
     */
    public String getAnnexDir() {
        return annexDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inform_list.annex_dir
     *
     * @param annexDir the value for inform_list.annex_dir
     *
     * @mbg.generated Sat Mar 02 16:55:26 CST 2019
     */
    public void setAnnexDir(String annexDir) {
        this.annexDir = annexDir == null ? null : annexDir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inform_list.annex_title
     *
     * @return the value of inform_list.annex_title
     *
     * @mbg.generated Sat Mar 02 16:55:26 CST 2019
     */
    public String getAnnexTitle() {
        return annexTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inform_list.annex_title
     *
     * @param annexTitle the value for inform_list.annex_title
     *
     * @mbg.generated Sat Mar 02 16:55:26 CST 2019
     */
    public void setAnnexTitle(String annexTitle) {
        this.annexTitle = annexTitle == null ? null : annexTitle.trim();
    }
}