package com.fanren.wx.app.pojo;

public class Major {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_list.major_ID
     *
     * @mbg.generated Sun Feb 10 15:03:36 CST 2019
     */
    private String majorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_list.name
     *
     * @mbg.generated Sun Feb 10 15:03:36 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_list.class_number
     *
     * @mbg.generated Sun Feb 10 15:03:36 CST 2019
     */
    private String classNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_list.teacher_number
     *
     * @mbg.generated Sun Feb 10 15:03:36 CST 2019
     */
    private String teacherNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_list.student_number
     *
     * @mbg.generated Sun Feb 10 15:03:36 CST 2019
     */
    private String studentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_list.college_ID
     *
     * @mbg.generated Sun Feb 10 15:03:36 CST 2019
     */
    private String collegeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_list.major_ID
     *
     * @return the value of major_list.major_ID
     *
     * @mbg.generated Sun Feb 10 15:03:36 CST 2019
     */
    public String getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_list.major_ID
     *
     * @param majorId the value for major_list.major_ID
     *
     * @mbg.generated Sun Feb 10 15:03:36 CST 2019
     */
    public void setMajorId(String majorId) {
        this.majorId = majorId == null ? null : majorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_list.name
     *
     * @return the value of major_list.name
     *
     * @mbg.generated Sun Feb 10 15:03:36 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_list.name
     *
     * @param name the value for major_list.name
     *
     * @mbg.generated Sun Feb 10 15:03:36 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_list.class_number
     *
     * @return the value of major_list.class_number
     *
     * @mbg.generated Sun Feb 10 15:03:36 CST 2019
     */
    public String getClassNumber() {
        return classNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_list.class_number
     *
     * @param classNumber the value for major_list.class_number
     *
     * @mbg.generated Sun Feb 10 15:03:36 CST 2019
     */
    public void setClassNumber(String classNumber) {
        this.classNumber = classNumber == null ? null : classNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_list.teacher_number
     *
     * @return the value of major_list.teacher_number
     *
     * @mbg.generated Sun Feb 10 15:03:36 CST 2019
     */
    public String getTeacherNumber() {
        return teacherNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_list.teacher_number
     *
     * @param teacherNumber the value for major_list.teacher_number
     *
     * @mbg.generated Sun Feb 10 15:03:36 CST 2019
     */
    public void setTeacherNumber(String teacherNumber) {
        this.teacherNumber = teacherNumber == null ? null : teacherNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_list.student_number
     *
     * @return the value of major_list.student_number
     *
     * @mbg.generated Sun Feb 10 15:03:36 CST 2019
     */
    public String getStudentNumber() {
        return studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_list.student_number
     *
     * @param studentNumber the value for major_list.student_number
     *
     * @mbg.generated Sun Feb 10 15:03:36 CST 2019
     */
    public void setStudentNumber(String studentNumber) {
        this.studentNumber = studentNumber == null ? null : studentNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_list.college_ID
     *
     * @return the value of major_list.college_ID
     *
     * @mbg.generated Sun Feb 10 15:03:36 CST 2019
     */
    public String getCollegeId() {
        return collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_list.college_ID
     *
     * @param collegeId the value for major_list.college_ID
     *
     * @mbg.generated Sun Feb 10 15:03:36 CST 2019
     */
    public void setCollegeId(String collegeId) {
        this.collegeId = collegeId == null ? null : collegeId.trim();
    }
}