package com.fanren.wx.app.pojo;

public class Report {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_list.report_ID
     *
     * @mbg.generated Mon Feb 11 21:01:38 CST 2019
     */
    private String reportId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_list.reporter
     *
     * @mbg.generated Mon Feb 11 21:01:38 CST 2019
     */
    private String reporter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_list.theme
     *
     * @mbg.generated Mon Feb 11 21:01:38 CST 2019
     */
    private String theme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_list.time
     *
     * @mbg.generated Mon Feb 11 21:01:38 CST 2019
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_list.number
     *
     * @mbg.generated Mon Feb 11 21:01:38 CST 2019
     */
    private String number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_list.report_ID
     *
     * @return the value of report_list.report_ID
     *
     * @mbg.generated Mon Feb 11 21:01:38 CST 2019
     */
    public String getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_list.report_ID
     *
     * @param reportId the value for report_list.report_ID
     *
     * @mbg.generated Mon Feb 11 21:01:38 CST 2019
     */
    public void setReportId(String reportId) {
        this.reportId = reportId == null ? null : reportId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_list.reporter
     *
     * @return the value of report_list.reporter
     *
     * @mbg.generated Mon Feb 11 21:01:38 CST 2019
     */
    public String getReporter() {
        return reporter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_list.reporter
     *
     * @param reporter the value for report_list.reporter
     *
     * @mbg.generated Mon Feb 11 21:01:38 CST 2019
     */
    public void setReporter(String reporter) {
        this.reporter = reporter == null ? null : reporter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_list.theme
     *
     * @return the value of report_list.theme
     *
     * @mbg.generated Mon Feb 11 21:01:38 CST 2019
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_list.theme
     *
     * @param theme the value for report_list.theme
     *
     * @mbg.generated Mon Feb 11 21:01:38 CST 2019
     */
    public void setTheme(String theme) {
        this.theme = theme == null ? null : theme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_list.time
     *
     * @return the value of report_list.time
     *
     * @mbg.generated Mon Feb 11 21:01:38 CST 2019
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_list.time
     *
     * @param time the value for report_list.time
     *
     * @mbg.generated Mon Feb 11 21:01:38 CST 2019
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_list.number
     *
     * @return the value of report_list.number
     *
     * @mbg.generated Mon Feb 11 21:01:38 CST 2019
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_list.number
     *
     * @param number the value for report_list.number
     *
     * @mbg.generated Mon Feb 11 21:01:38 CST 2019
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }
}