package com.fanren.wx.app.pojo;

public class Resource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_list.resource_id
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    private Integer resourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_list.resource_name
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    private String resourceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_list.resource_dir
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    private String resourceDir;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_list.uploader_id
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    private String uploaderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_list.uploader_name
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    private String uploaderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_list.upload_time
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    private String uploadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_list.download_number
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    private String downloadNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_list.resource_id
     *
     * @return the value of resource_list.resource_id
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    public Integer getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_list.resource_id
     *
     * @param resourceId the value for resource_list.resource_id
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_list.resource_name
     *
     * @return the value of resource_list.resource_name
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_list.resource_name
     *
     * @param resourceName the value for resource_list.resource_name
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_list.resource_dir
     *
     * @return the value of resource_list.resource_dir
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    public String getResourceDir() {
        return resourceDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_list.resource_dir
     *
     * @param resourceDir the value for resource_list.resource_dir
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    public void setResourceDir(String resourceDir) {
        this.resourceDir = resourceDir == null ? null : resourceDir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_list.uploader_id
     *
     * @return the value of resource_list.uploader_id
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    public String getUploaderId() {
        return uploaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_list.uploader_id
     *
     * @param uploaderId the value for resource_list.uploader_id
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    public void setUploaderId(String uploaderId) {
        this.uploaderId = uploaderId == null ? null : uploaderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_list.uploader_name
     *
     * @return the value of resource_list.uploader_name
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    public String getUploaderName() {
        return uploaderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_list.uploader_name
     *
     * @param uploaderName the value for resource_list.uploader_name
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    public void setUploaderName(String uploaderName) {
        this.uploaderName = uploaderName == null ? null : uploaderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_list.upload_time
     *
     * @return the value of resource_list.upload_time
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    public String getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_list.upload_time
     *
     * @param uploadTime the value for resource_list.upload_time
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    public void setUploadTime(String uploadTime) {
        this.uploadTime = uploadTime == null ? null : uploadTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_list.download_number
     *
     * @return the value of resource_list.download_number
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    public String getDownloadNumber() {
        return downloadNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_list.download_number
     *
     * @param downloadNumber the value for resource_list.download_number
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    public void setDownloadNumber(String downloadNumber) {
        this.downloadNumber = downloadNumber == null ? null : downloadNumber.trim();
    }
}