package com.fanren.wx.app.pojo;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_list.student_ID
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_list.name
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_list.sex
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_list.ID_Card
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_list.phone
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_list.department
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_list.major
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_list.classes
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    private String classes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_list.qq
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_list.wx
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    private String wx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_list.student_ID
     *
     * @return the value of student_list.student_ID
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_list.student_ID
     *
     * @param studentId the value for student_list.student_ID
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_list.name
     *
     * @return the value of student_list.name
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_list.name
     *
     * @param name the value for student_list.name
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_list.sex
     *
     * @return the value of student_list.sex
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_list.sex
     *
     * @param sex the value for student_list.sex
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_list.ID_Card
     *
     * @return the value of student_list.ID_Card
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_list.ID_Card
     *
     * @param idCard the value for student_list.ID_Card
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_list.phone
     *
     * @return the value of student_list.phone
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_list.phone
     *
     * @param phone the value for student_list.phone
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_list.department
     *
     * @return the value of student_list.department
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_list.department
     *
     * @param department the value for student_list.department
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_list.major
     *
     * @return the value of student_list.major
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_list.major
     *
     * @param major the value for student_list.major
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_list.classes
     *
     * @return the value of student_list.classes
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    public String getClasses() {
        return classes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_list.classes
     *
     * @param classes the value for student_list.classes
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    public void setClasses(String classes) {
        this.classes = classes == null ? null : classes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_list.qq
     *
     * @return the value of student_list.qq
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_list.qq
     *
     * @param qq the value for student_list.qq
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_list.wx
     *
     * @return the value of student_list.wx
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    public String getWx() {
        return wx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_list.wx
     *
     * @param wx the value for student_list.wx
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    public void setWx(String wx) {
        this.wx = wx == null ? null : wx.trim();
    }
}