package com.fanren.wx.app.pojo;

public class Teacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_list.teacher_ID
     *
     * @mbg.generated Mon Feb 11 12:08:52 CST 2019
     */
    private String teacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_list.name
     *
     * @mbg.generated Mon Feb 11 12:08:52 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_list.sex
     *
     * @mbg.generated Mon Feb 11 12:08:52 CST 2019
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_list.ID_Card
     *
     * @mbg.generated Mon Feb 11 12:08:52 CST 2019
     */
    private String idCard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_list.teacher_ID
     *
     * @return the value of teacher_list.teacher_ID
     *
     * @mbg.generated Mon Feb 11 12:08:52 CST 2019
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_list.teacher_ID
     *
     * @param teacherId the value for teacher_list.teacher_ID
     *
     * @mbg.generated Mon Feb 11 12:08:52 CST 2019
     */
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId == null ? null : teacherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_list.name
     *
     * @return the value of teacher_list.name
     *
     * @mbg.generated Mon Feb 11 12:08:52 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_list.name
     *
     * @param name the value for teacher_list.name
     *
     * @mbg.generated Mon Feb 11 12:08:52 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_list.sex
     *
     * @return the value of teacher_list.sex
     *
     * @mbg.generated Mon Feb 11 12:08:52 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_list.sex
     *
     * @param sex the value for teacher_list.sex
     *
     * @mbg.generated Mon Feb 11 12:08:52 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_list.ID_Card
     *
     * @return the value of teacher_list.ID_Card
     *
     * @mbg.generated Mon Feb 11 12:08:52 CST 2019
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_list.ID_Card
     *
     * @param idCard the value for teacher_list.ID_Card
     *
     * @mbg.generated Mon Feb 11 12:08:52 CST 2019
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }
}