package com.fanren.wx.app.pojo;

public class Teacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_list.teacher_ID
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    private String teacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_list.name
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_list.sex
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_list.ID_Card
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_list.phone
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_list.email
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_list.qq
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_list.degree
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    private String degree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_list.department
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_list.teach_curriculum
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    private String teachCurriculum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_list.teacher_ID
     *
     * @return the value of teacher_list.teacher_ID
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_list.teacher_ID
     *
     * @param teacherId the value for teacher_list.teacher_ID
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId == null ? null : teacherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_list.name
     *
     * @return the value of teacher_list.name
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_list.name
     *
     * @param name the value for teacher_list.name
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_list.sex
     *
     * @return the value of teacher_list.sex
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_list.sex
     *
     * @param sex the value for teacher_list.sex
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_list.ID_Card
     *
     * @return the value of teacher_list.ID_Card
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_list.ID_Card
     *
     * @param idCard the value for teacher_list.ID_Card
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_list.phone
     *
     * @return the value of teacher_list.phone
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_list.phone
     *
     * @param phone the value for teacher_list.phone
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_list.email
     *
     * @return the value of teacher_list.email
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_list.email
     *
     * @param email the value for teacher_list.email
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_list.qq
     *
     * @return the value of teacher_list.qq
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_list.qq
     *
     * @param qq the value for teacher_list.qq
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_list.degree
     *
     * @return the value of teacher_list.degree
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_list.degree
     *
     * @param degree the value for teacher_list.degree
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    public void setDegree(String degree) {
        this.degree = degree == null ? null : degree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_list.department
     *
     * @return the value of teacher_list.department
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_list.department
     *
     * @param department the value for teacher_list.department
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_list.teach_curriculum
     *
     * @return the value of teacher_list.teach_curriculum
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    public String getTeachCurriculum() {
        return teachCurriculum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_list.teach_curriculum
     *
     * @param teachCurriculum the value for teacher_list.teach_curriculum
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    public void setTeachCurriculum(String teachCurriculum) {
        this.teachCurriculum = teachCurriculum == null ? null : teachCurriculum.trim();
    }
}