package com.fanren.wx.app.dao;

import com.fanren.wx.app.pojo.Attend;
import com.fanren.wx.app.pojo.AttendExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface AttendMapper {
    //查询所有旷课学生信息
    List<Attend> attend_list();
    //查询旷课学生数量
    int attend_number();
    //根据学号更新学生信息
    void attend_update(Attend attend);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attend_list
     *
     * @mbg.generated Sat Mar 02 14:55:13 CST 2019
     */
    long countByExample(AttendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attend_list
     *
     * @mbg.generated Sat Mar 02 14:55:13 CST 2019
     */
    int deleteByExample(AttendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attend_list
     *
     * @mbg.generated Sat Mar 02 14:55:13 CST 2019
     */
    int insert(Attend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attend_list
     *
     * @mbg.generated Sat Mar 02 14:55:13 CST 2019
     */
    int insertSelective(Attend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attend_list
     *
     * @mbg.generated Sat Mar 02 14:55:13 CST 2019
     */
    List<Attend> selectByExample(AttendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attend_list
     *
     * @mbg.generated Sat Mar 02 14:55:13 CST 2019
     */
    int updateByExampleSelective(@Param("record") Attend record, @Param("example") AttendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attend_list
     *
     * @mbg.generated Sat Mar 02 14:55:13 CST 2019
     */
    int updateByExample(@Param("record") Attend record, @Param("example") AttendExample example);
}