package com.fanren.wx.app.dao;

import com.fanren.wx.app.pojo.Badworld;
import com.fanren.wx.app.pojo.BadworldExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Set;

@Repository
public interface BadworldMapper {
    //查询所有敏感词返回字符
    Set<String> badworld_list_string();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table badworld_list
     *
     * @mbg.generated Thu Feb 21 12:44:58 CST 2019
     */
    long countByExample(BadworldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table badworld_list
     *
     * @mbg.generated Thu Feb 21 12:44:58 CST 2019
     */
    int deleteByExample(BadworldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table badworld_list
     *
     * @mbg.generated Thu Feb 21 12:44:58 CST 2019
     */
    int insert(Badworld record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table badworld_list
     *
     * @mbg.generated Thu Feb 21 12:44:58 CST 2019
     */
    int insertSelective(Badworld record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table badworld_list
     *
     * @mbg.generated Thu Feb 21 12:44:58 CST 2019
     */
    List<Badworld> selectByExample(BadworldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table badworld_list
     *
     * @mbg.generated Thu Feb 21 12:44:58 CST 2019
     */
    int updateByExampleSelective(@Param("record") Badworld record, @Param("example") BadworldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table badworld_list
     *
     * @mbg.generated Thu Feb 21 12:44:58 CST 2019
     */
    int updateByExample(@Param("record") Badworld record, @Param("example") BadworldExample example);
}