package com.fanren.wx.app.dao;

import com.fanren.wx.app.pojo.College;
import com.fanren.wx.app.pojo.CollegeExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface CollegeMapper {
    //根据院系编号更新院系名称
    void college_update(College college);
    //查询院系数量
    int college_number();
    //查询所有院系信息
    List<College> college_list();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college_list
     *
     * @mbg.generated Thu Jan 31 09:50:32 CST 2019
     */
    long countByExample(CollegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college_list
     *
     * @mbg.generated Thu Jan 31 09:50:32 CST 2019
     */
    int deleteByExample(CollegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college_list
     *
     * @mbg.generated Thu Jan 31 09:50:32 CST 2019
     */
    int deleteByPrimaryKey(String collegeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college_list
     *
     * @mbg.generated Thu Jan 31 09:50:32 CST 2019
     */
    int insert(College record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college_list
     *
     * @mbg.generated Thu Jan 31 09:50:32 CST 2019
     */
    int insertSelective(College record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college_list
     *
     * @mbg.generated Thu Jan 31 09:50:32 CST 2019
     */
    List<College> selectByExample(CollegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college_list
     *
     * @mbg.generated Thu Jan 31 09:50:32 CST 2019
     */
    College selectByPrimaryKey(String collegeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college_list
     *
     * @mbg.generated Thu Jan 31 09:50:32 CST 2019
     */
    int updateByExampleSelective(@Param("record") College record, @Param("example") CollegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college_list
     *
     * @mbg.generated Thu Jan 31 09:50:32 CST 2019
     */
    int updateByExample(@Param("record") College record, @Param("example") CollegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college_list
     *
     * @mbg.generated Thu Jan 31 09:50:32 CST 2019
     */
    int updateByPrimaryKeySelective(College record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college_list
     *
     * @mbg.generated Thu Jan 31 09:50:32 CST 2019
     */
    int updateByPrimaryKey(College record);
}