package com.fanren.wx.app.dao;

import com.fanren.wx.app.pojo.Exam;
import com.fanren.wx.app.pojo.ExamExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ExamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_list
     *
     * @mbg.generated Sat Mar 02 14:58:00 CST 2019
     */
    long countByExample(ExamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_list
     *
     * @mbg.generated Sat Mar 02 14:58:00 CST 2019
     */
    int deleteByExample(ExamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_list
     *
     * @mbg.generated Sat Mar 02 14:58:00 CST 2019
     */
    int insert(Exam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_list
     *
     * @mbg.generated Sat Mar 02 14:58:00 CST 2019
     */
    int insertSelective(Exam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_list
     *
     * @mbg.generated Sat Mar 02 14:58:00 CST 2019
     */
    List<Exam> selectByExample(ExamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_list
     *
     * @mbg.generated Sat Mar 02 14:58:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") Exam record, @Param("example") ExamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_list
     *
     * @mbg.generated Sat Mar 02 14:58:00 CST 2019
     */
    int updateByExample(@Param("record") Exam record, @Param("example") ExamExample example);
}