package com.fanren.wx.app.dao;

import com.fanren.wx.app.pojo.Inform;
import com.fanren.wx.app.pojo.InformExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface InformMapper {
    //更新通知信息
    void inform_update(Inform inform);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform_list
     *
     * @mbg.generated Sat Mar 02 16:55:26 CST 2019
     */
    long countByExample(InformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform_list
     *
     * @mbg.generated Sat Mar 02 16:55:26 CST 2019
     */
    int deleteByExample(InformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform_list
     *
     * @mbg.generated Sat Mar 02 16:55:26 CST 2019
     */
    int insert(Inform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform_list
     *
     * @mbg.generated Sat Mar 02 16:55:26 CST 2019
     */
    int insertSelective(Inform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform_list
     *
     * @mbg.generated Sat Mar 02 16:55:26 CST 2019
     */
    List<Inform> selectByExample(InformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform_list
     *
     * @mbg.generated Sat Mar 02 16:55:26 CST 2019
     */
    int updateByExampleSelective(@Param("record") Inform record, @Param("example") InformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inform_list
     *
     * @mbg.generated Sat Mar 02 16:55:26 CST 2019
     */
    int updateByExample(@Param("record") Inform record, @Param("example") InformExample example);
}