package com.fanren.wx.app.dao;

import com.fanren.wx.app.pojo.Major;
import com.fanren.wx.app.pojo.MajorExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface MajorMapper {
    //查询所有专业信息
    List<Major> major_list();
    //查询所有专业数量
    int major_number();
    //根据专业编号更新信息
    void update_major(Major major);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_list
     *
     * @mbg.generated Sun Feb 10 15:03:36 CST 2019
     */
    long countByExample(MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_list
     *
     * @mbg.generated Sun Feb 10 15:03:36 CST 2019
     */
    int deleteByExample(MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_list
     *
     * @mbg.generated Sun Feb 10 15:03:36 CST 2019
     */
    int deleteByPrimaryKey(String majorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_list
     *
     * @mbg.generated Sun Feb 10 15:03:36 CST 2019
     */
    int insert(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_list
     *
     * @mbg.generated Sun Feb 10 15:03:36 CST 2019
     */
    int insertSelective(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_list
     *
     * @mbg.generated Sun Feb 10 15:03:36 CST 2019
     */
    List<Major> selectByExample(MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_list
     *
     * @mbg.generated Sun Feb 10 15:03:36 CST 2019
     */
    Major selectByPrimaryKey(String majorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_list
     *
     * @mbg.generated Sun Feb 10 15:03:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") Major record, @Param("example") MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_list
     *
     * @mbg.generated Sun Feb 10 15:03:36 CST 2019
     */
    int updateByExample(@Param("record") Major record, @Param("example") MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_list
     *
     * @mbg.generated Sun Feb 10 15:03:36 CST 2019
     */
    int updateByPrimaryKeySelective(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_list
     *
     * @mbg.generated Sun Feb 10 15:03:36 CST 2019
     */
    int updateByPrimaryKey(Major record);
}