package com.fanren.wx.app.dao;

import com.fanren.wx.app.pojo.Report;
import com.fanren.wx.app.pojo.ReportExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ReportMapper {
    //根据报告会编号修改报告会信息
    void report_update(Report report);
    //查村所有报告会数量
    int report_number();
    //查询所有报告会
    List<Report> report_list();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_list
     *
     * @mbg.generated Mon Feb 11 21:01:38 CST 2019
     */
    long countByExample(ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_list
     *
     * @mbg.generated Mon Feb 11 21:01:38 CST 2019
     */
    int deleteByExample(ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_list
     *
     * @mbg.generated Mon Feb 11 21:01:38 CST 2019
     */
    int deleteByPrimaryKey(String reportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_list
     *
     * @mbg.generated Mon Feb 11 21:01:38 CST 2019
     */
    int insert(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_list
     *
     * @mbg.generated Mon Feb 11 21:01:38 CST 2019
     */
    int insertSelective(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_list
     *
     * @mbg.generated Mon Feb 11 21:01:38 CST 2019
     */
    List<Report> selectByExample(ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_list
     *
     * @mbg.generated Mon Feb 11 21:01:38 CST 2019
     */
    Report selectByPrimaryKey(String reportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_list
     *
     * @mbg.generated Mon Feb 11 21:01:38 CST 2019
     */
    int updateByExampleSelective(@Param("record") Report record, @Param("example") ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_list
     *
     * @mbg.generated Mon Feb 11 21:01:38 CST 2019
     */
    int updateByExample(@Param("record") Report record, @Param("example") ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_list
     *
     * @mbg.generated Mon Feb 11 21:01:38 CST 2019
     */
    int updateByPrimaryKeySelective(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_list
     *
     * @mbg.generated Mon Feb 11 21:01:38 CST 2019
     */
    int updateByPrimaryKey(Report record);
}