package com.fanren.wx.app.dao;

import com.fanren.wx.app.pojo.Resource;
import com.fanren.wx.app.pojo.ResourceExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ResourceMapper {
    //更新资源下载数量
    void resource_update_number(Resource resource);
    //根据资源名称查询资源
    Resource GetResource(String name);
    //查询所有资源数量
    int resource_number();
    //查询所有资源信息
    List<Resource> resource_list();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_list
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    long countByExample(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_list
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    int deleteByExample(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_list
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    int deleteByPrimaryKey(Integer resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_list
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    int insert(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_list
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    int insertSelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_list
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    List<Resource> selectByExample(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_list
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    Resource selectByPrimaryKey(Integer resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_list
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") Resource record, @Param("example") ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_list
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    int updateByExample(@Param("record") Resource record, @Param("example") ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_list
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    int updateByPrimaryKeySelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_list
     *
     * @mbg.generated Wed Feb 20 11:56:00 CST 2019
     */
    int updateByPrimaryKey(Resource record);
}