package com.fanren.wx.app.dao;

import com.fanren.wx.app.pojo.Student;
import com.fanren.wx.app.pojo.StudentExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_list
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    long countByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_list
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    int deleteByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_list
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    int deleteByPrimaryKey(String studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_list
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_list
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_list
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    List<Student> selectByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_list
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    Student selectByPrimaryKey(String studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_list
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") Student record, @Param("example") StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_list
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    int updateByExample(@Param("record") Student record, @Param("example") StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_list
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_list
     *
     * @mbg.generated Wed Feb 27 14:42:15 CST 2019
     */
    int updateByPrimaryKey(Student record);
}