package com.fanren.wx.app.dao;

import com.fanren.wx.app.pojo.Teacher;
import com.fanren.wx.app.pojo.TeacherExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface TeacherMapper {
    //根据教师编号修改教师信息
    void teacher_update(Teacher teacher);
    //查询教师数量
    int teacher_number();
    //查询所有教师信息
    List<Teacher> teacher_list();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_list
     *
     * @mbg.generated Mon Feb 11 12:08:52 CST 2019
     */
    long countByExample(TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_list
     *
     * @mbg.generated Mon Feb 11 12:08:52 CST 2019
     */
    int deleteByExample(TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_list
     *
     * @mbg.generated Mon Feb 11 12:08:52 CST 2019
     */
    int deleteByPrimaryKey(String teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_list
     *
     * @mbg.generated Mon Feb 11 12:08:52 CST 2019
     */
    int insert(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_list
     *
     * @mbg.generated Mon Feb 11 12:08:52 CST 2019
     */
    int insertSelective(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_list
     *
     * @mbg.generated Mon Feb 11 12:08:52 CST 2019
     */
    List<Teacher> selectByExample(TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_list
     *
     * @mbg.generated Mon Feb 11 12:08:52 CST 2019
     */
    Teacher selectByPrimaryKey(String teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_list
     *
     * @mbg.generated Mon Feb 11 12:08:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") Teacher record, @Param("example") TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_list
     *
     * @mbg.generated Mon Feb 11 12:08:52 CST 2019
     */
    int updateByExample(@Param("record") Teacher record, @Param("example") TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_list
     *
     * @mbg.generated Mon Feb 11 12:08:52 CST 2019
     */
    int updateByPrimaryKeySelective(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_list
     *
     * @mbg.generated Mon Feb 11 12:08:52 CST 2019
     */
    int updateByPrimaryKey(Teacher record);
}