package com.fanren.wx.app.dao;

import com.fanren.wx.app.pojo.Teacher;
import com.fanren.wx.app.pojo.TeacherExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface TeacherMapper {

    List<Teacher> getTeacherInfoByNameOrCurr(String NameOrCurr);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_list
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    long countByExample(TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_list
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    int deleteByExample(TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_list
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    int insert(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_list
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    int insertSelective(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_list
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    List<Teacher> selectByExample(TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_list
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    int updateByExampleSelective(@Param("record") Teacher record, @Param("example") TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_list
     *
     * @mbg.generated Mon Mar 04 16:52:42 CST 2019
     */
    int updateByExample(@Param("record") Teacher record, @Param("example") TeacherExample example);
}